# Generated by Django 5.1.4 on 2024-12-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=30)),
                ('music', models.FileField(upload_to='')),
            ],
        ),
    ]
