# Generated by Django 5.1.4 on 2024-12-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music',
        ),
        migrations.RemoveField(
            model_name='music',
            name='name',
        ),
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='music',
            name='writer',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
