# Generated by Django 5.1.4 on 2024-12-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_music_cover_alter_music_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='writer',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
