# Generated by Django 5.1.4 on 2024-12-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_music_cover_alter_music_file_alter_music_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.FileField(default=None, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(default=None, upload_to='music'),
        ),
    ]
