# Generated by Django 5.1.4 on 2024-12-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite_music',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
