# Generated by Django 5.1.4 on 2024-12-20 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_account_favorite_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.music')),
            ],
        ),
    ]
