# Generated by Django 5.1.4 on 2024-12-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_usedmusic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsedMusic',
        ),
    ]
